Added filtration to controller "Registration"
Kirel-tech/Kirel.Identity pull request #32
Opened 2023-08-15 14:48 UTC by Grimooar

*Added propertu status in Appsettings 
*aplying filter in controller

2023-08-16 07:50 UTC, Insei requested changes

2023-08-16 07:50 UTC, Insei commented on src/Kirel.Identity.Server.API/appsettings.json
> +  "ControllerState": {
I think, we should rename this property name, and use something like:
"RegistrationEnable":  true/false, without info about controllers and other details of the implementations.

2023-08-16 07:50 UTC, Insei commented on src/Kirel.Identity.Server.Core/Extensions/ServicesExtension.cs
> +    public static void AddServices(this IServiceCollection services, JwtAuthenticationConfig jwtConfig  )
thy you add space here? i think it's not needed

2023-08-16 07:50 UTC, Insei commented on src/Kirel.Identity.Server.Core/Filters/EnableIfSettingFilter.cs
> +public class EnableIfSettingAttribute : Attribute, IActionFilter
Why not simply EnabledControllerAttribute? I think this name will be prefer.

2023-08-16 07:50 UTC, Insei commented on src/Kirel.Identity.Server.API/Controllers/RegistrationController.cs
> +[ApiExplorerSettings(IgnoreApi = true)]
Why we ignore this cantroller always in swagger? It's not correct, if we enable this controller in settings, we should show swagger documentation for him.

2023-08-16 11:12 UTC, Grimooar commented
fully working version without any issues

2023-08-20 15:15 UTC, Insei commented
Closed, we have a new one: https://github.com/Kirel-tech/Kirel.Identity/pull/35

2023-08-20 15:15 UTC, closed without merging